[package]
name = "amcpms-app"
version = "0.1.0"
edition = "2021"
authors = ["HTGAzureX1212."]
license = "GPL-3.0 only"
rust-version = "1.76.0"

[dependencies]
amcpms-core = { path = "../amcpms-core" }
